# BERT Pretraining
trainer:
  gpus: 1 # the number of gpus, 0 for CPU, or list with gpu indices
  num_nodes: 1
  max_epochs: 2 # the number of training epochs
  max_steps: null # precedence over max_epochs
  accumulate_grad_batches: 1 # accumulates grads every k batches
  precision: 16 # 16 to use AMP
  amp_level: O1 # O1 or O2 if using AMP 
  distributed_backend: ddp
  gradient_clip_val: 0.0
  val_check_interval: 1.0 # check once per epoch .25 for 4 times per epoch
  checkpoint_callback: false # provided by exp_manager
  logger: false # provided by exp_manager

model:

  max_seq_length: 128
  # The maximum total input sequence length after
  # WordPiece tokenization. Sequences longer than this
  # will be truncated, and sequences shorter than this
  # will be padded.

  sample_size: 1e7
  # Data sample size.

  mask_probability: 0.15
  # Probability of masking a token in the input text during data processing.

  short_seq_prob: 0.1
  # Probability of having a sequence shorter than the maximum sequence length `max_seq_length` in data processing.",
   
  train_ds:
    mode: train
    file: null # .json file
    batch_size: 24 # per GPU
    shuffle: true
    num_samples: -1
    num_workers: 2
    use_cache: true
    drop_last: false
    pin_memory: false
    max_answer_length: null
    # The maximum length of an answer that can be 
    # generated. This is needed because the start
    # and end predictions are not conditioned
    # on one another.
    output_prediction_file: null
    # File to write predictions to. Only in evaluation or test mode,
    output_nbest_file: null
    # File to write nbest predictions to. Only in evaluation or test mode.
    null_score_diff_threshold: null
    # If null_score - best_non_null is greater than the threshold predict null.
    n_best_size: null
    # The total number of n-best predictions to generate at testing.

  validation_ds:
    mode: eval
    file: null # .json file
    batch_size: 24 # per GPU
    shuffle: false
    num_samples: -1
    num_workers: 2
    use_cache: true
    drop_last: false
    pin_memory: false
    max_answer_length: 30
    # The maximum length of an answer that can be 
    # generated. This is needed because the start
    # and end predictions are not conditioned
    # on one another.
    output_prediction_file: predictions.json
    # File to write predictions to. Only in evaluation or test mode,
    output_nbest_file: nbest.json
    # File to write nbest predictions to. Only in evaluation or test mode.
    null_score_diff_threshold: 0.0
    # If null_score - best_non_null is greater than the threshold predict null.
    n_best_size: 20
    # The total number of n-best predictions to generate at testing.
  
  optim:
    name: adamw
    lr: 3e-5
    args:
      name: auto
      params:
        weight_decay: 0.0

    sched:
      name: SquareRootAnnealing
      iters_per_batch: null # computed at runtime
      max_steps: null # computed at runtime or explicitly set here

      # pytorch lightning args
      monitor: val_loss
      reduce_on_plateau: false

      # scheduler config override
      args:
        name: auto
        params:
          warmup_steps: null
          warmup_ratio: 0.1
          last_epoch: -1


  language_model:
    pretrained_model_name: bert-base-uncased
    bert_checkpoint: null
    bert_config: null
    tokenizer: nemobert # only used if using custom checkpoint
    tokenizer_model: null # only used if tokenizer is sentencepiece
    vocab_file: null
    do_lower_case: true # true for uncased models, false for cased models
  
  token_classifier:
    num_layers: 1
    dropout: 0.0
    num_classes: 2
    activation: relu
    log_softmax: false
    use_transformer_init: true

  pl: null # used at runtime

exp_manager:
  root_dir: null # where to store logs and checkpoints
  name: PretrainingBERT # name of experiment
  create_tensorboard_logger: True
  create_checkpoint_callback: True

hydra:
  run:
    dir: .
  job_logging:
    root:
      handlers: null